// Mocks generated by Mockito 5.4.4 from annotations
// in coinvert/test/repositories/articles_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coinvert/data/datasources/local/exchange_local_datasource.dart'
    as _i5;
import 'package:coinvert/data/datasources/remote/exchange_remote_datasource.dart'
    as _i3;
import 'package:coinvert/data/models/responses/exchange_rate_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExchangeRateModel_0 extends _i1.SmartFake
    implements _i2.ExchangeRateModel {
  _FakeExchangeRateModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExchangeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRemoteDataSource extends _i1.Mock
    implements _i3.ExchangeRemoteDataSource {
  MockExchangeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExchangeRateModel> getExchangeRates(String? currency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExchangeRates,
          [currency],
        ),
        returnValue:
            _i4.Future<_i2.ExchangeRateModel>.value(_FakeExchangeRateModel_0(
          this,
          Invocation.method(
            #getExchangeRates,
            [currency],
          ),
        )),
      ) as _i4.Future<_i2.ExchangeRateModel>);
}

/// A class which mocks [ExchangeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeLocalDataSource extends _i1.Mock
    implements _i5.ExchangeLocalDataSource {
  MockExchangeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExchangeRateModel?> getExchangeRates() => (super.noSuchMethod(
        Invocation.method(
          #getExchangeRates,
          [],
        ),
        returnValue: _i4.Future<_i2.ExchangeRateModel?>.value(),
      ) as _i4.Future<_i2.ExchangeRateModel?>);

  @override
  _i4.Future<void> setExchangeRates(_i2.ExchangeRateModel? exchangeRateModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExchangeRates,
          [exchangeRateModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
